name: Lint & Type Check

on:
  push:
    branches: ["main", "feat/*"]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff mypy

      - name: Run Ruff (lint + format check)
        run: ruff check src tests

      - name: Run MyPy (type checking)
        run: mypy src
